// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltcrcjzutdxqeycboohf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Y3Jjanp1dGR4cWV5Y2Jvb2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTk3MzEsImV4cCI6MjA2NTI5NTczMX0.FW7RdRg6eIOQwx6eB_Ag8ury0Pf84Pm6m4K30xxIhXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);